name: deploy
on:
  workflow_run:
    workflows: ["Pylint", "Pytest"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: remote-ssh
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: http://ec2-3-38-244-160.ap-northeast-2.compute.amazonaws.com
        username: ec2-user
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: whoami
